# fly.toml file generated for reactivities-lla on 2023-03-09T14:53:56-05:00

app = "reactivities-lla"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yyz"
processes = []

[build]
  image = "spandon/reactivities:latest"

[env]
  ASNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dafz3nsob"
  Cloudinary__ApiKey="527635945156896"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
